name: Release


on:
    workflow_dispatch: {}
    push:
        tags:
            - "v*.*.*"

jobs:
    release-gh:
        name: Github Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
            - name: Install Nix
              uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
              with:
                nix_path: nixpkgs=channel:nixos-unstable
                extra_nix_config: "sandbox = false"
            - run: nix develop -c yarn install --frozen-lockfile
            - run: nix develop -c yarn build
            - run: nix develop -c tar -czvf artifacts.tar.gz artifacts
            - name: Upload
              uses: softprops/action-gh-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: |
                    artifacts.tar.gz


        






